export * from './ping.controller';
export * from './clientes.controller';
export * from './tecnicos.controller';
export * from './procesadores.controller';
export * from './sistemas-operativos.controller';
export * from './computadoras.controller';
export * from './mantenimientos.controller';
export * from './proximos-mantenimientos.controller';
export * from './reparaciones.controller';
